export const categories = [
  { id: 1, name: "All" },
  { id: 2, name: "APIs" },
  { id: 3, name: "Templates" },
  { id: 4, name: "Graphics" },
  { id: 5, name: "Software" },
  { id: 6, name: "Extensions" },
  { id: 7, name: "eBooks" },
  { id: 8, name: "Online Courses" },
  { id: 9, name: "Plugins" },
  { id: 10, name: "Stock Photos" },
  { id: 11, name: "Stock Videos" },
  { id: 12, name: "Music" },
  { id: 13, name: "Sound Effects" },
  { id: 14, name: "Digital Marketing Tools" },
];

export const assets = [
  {
    id: 1,
    category: "templates",
    name: "Some Template",
    description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
    price: "50",
  },
  {
    id: 2,
    category: "apis",
    name: "Some API",
    description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
    price: "5",
  },
  {
    id: 3,
    category: "graphics",
    name: "Some Graphic",
    description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
    price: "10",
  },
  {
    id: 4,
    category: "software",
    name: "Some Software",
    description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
    price: "30",
  },
  {
    id: 5,
    category: "templates",
    name: "Some Template",
    description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
    price: "45",
  },
  {
    id: 6,
    category: "graphics",
    name: "Some Graphic",
    description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
    price: "15",
  },
  {
    id: 7,
    category: "graphics",
    name: "Some Graphic",
    description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit.",
    price: "7",
  },
];
